### ISSUE TITLE
Error when adding scan_interval.

### ISSUE THREAD

**Issue by perern** [dennyreiter/hass-gmaps#2]
device_tracker:
  - platform: gmaps
    username: xxxxxxxxxxxxxxxxxx
    scan_interval: 41

This gives:
Invalid config for [device_tracker.gmaps]: expected float for dictionary value @ data['scan_interval']. Got datetime.timedelta(0, 41). (See ?, line ?). Please check the docs at https://home-assistant.io/components/device_tracker.gmaps/

**Comment by crimean7** [comment]
Hi there,
Hope you can help me with that. I'm getting an ERROR (SyncWorker_13) [custom_components.gmaps.device_tracker] You have specified invalid login credentials.

- Home Assistant on Raspberry Pi in Virtual Environment
- Got cookie file with Chrome extension. Can't get to work mapscookiegettercli with a response:

2019-08-02 16:36:59 hassio cookiegetter.CookieGetter[4256] INFO Identified OS as linux
Traceback (most recent call last):
  File "/srv/homeassistant/bin/maps-cookie-getter", line 10, in <module>
    sys.exit(main())
  File "/srv/homeassistant/lib/python3.7/site-packages/mapscookiegettercli/mapscookiegettercli.py", line 91, in main
    getter = CookieGetter()
  File "/srv/homeassistant/lib/python3.7/site-packages/mapscookiegettercli/library/cookiegetter.py", line 81, in __init__
    self.default_browser = self._identify_default_browser(self.os)
  File "/srv/homeassistant/lib/python3.7/site-packages/mapscookiegettercli/library/cookiegetter.py", line 101, in _identify_default_browser
    raise UnsupportedDefaultBrowser
mapscookiegettercli.mapscookiegettercliexceptions.UnsupportedDefaultBrowser

Home you can direct me to a method to solve the issue.

Thanks
