### ISSUE TITLE
ERROR (SyncWorker_13) [custom_components.gmaps.device_tracker] You have specified invalid login credentials

### ISSUE THREAD

**Issue by crimean7** [dennyreiter/hass-gmaps#3]
Hi there,
Hope you can help me with that. I'm getting an ERROR (SyncWorker_13) [custom_components.gmaps.device_tracker] You have specified invalid login credentials.

Home Assistant on Raspberry Pi in Virtual Environment
Got cookie file with Chrome extension. Can't get to work mapscookiegettercli with a response:
2019-08-02 16:36:59 hassio cookiegetter.CookieGetter[4256] INFO Identified OS as linux
Traceback (most recent call last):
File "/srv/homeassistant/bin/maps-cookie-getter", line 10, in
sys.exit(main())
File "/srv/homeassistant/lib/python3.7/site-packages/mapscookiegettercli/mapscookiegettercli.py", line 91, in main
getter = CookieGetter()
File "/srv/homeassistant/lib/python3.7/site-packages/mapscookiegettercli/library/cookiegetter.py", line 81, in init
self.default_browser = self._identify_default_browser(self.os)
File "/srv/homeassistant/lib/python3.7/site-packages/mapscookiegettercli/library/cookiegetter.py", line 101, in _identify_default_browser
raise UnsupportedDefaultBrowser
mapscookiegettercli.mapscookiegettercliexceptions.UnsupportedDefaultBrowser

And, I have Firefox installed as the Chromium isn't supported.

Home you can direct me to a method to solve the issue.

Thanks

**Comment by crimean7** [comment]
Tried now with different gmail account. No errors in the log. However, no device_trackers are discovered and known_devices.yaml is empty.
